apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/auth
    repoURL: 'git@github.com:Magisterka-Maurycy/GitOps.git'
    targetRevision: 0.1.3
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
    automated:
      prune: false
      selfHeal: false
