apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 'prometheus'
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus
      targetRevision: 15.7.1
      helm:
        valueFiles:
          - $values/kubernetes/prometheus/values.yaml
    - repoURL: 'git@github.com:Magisterka-Maurycy/GitOps.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated: { }