version: '3.5'

services:
  dsa:
    image: quay.io/maurycy_krzeminski/dsa:0.1.1
    ports:
      - "8080:8080"
    environment:
      QUARKUS_LOG_HANDLER_GELF_ENABLED: "false"
      DISABLE_AUTHORIZATION: "true"
  dsa-elastic:
    image: elastic/elasticsearch:7.16.3
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MagicWord"
      xpack.security.enabled: "true"
  dsa-minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    environment:
    - MINIO_ROOT_PASSWORD=CHANGEME123
    - MINIO_ROOT_USER=ROOTUSER
