apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dsa-minio
  name: dsa-minio
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: dsa-minio
