apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dsa-elastic
  name: dsa-elastic
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    io.kompose.service: dsa-elastic
