version: '3.5'

services:
  auth:
    image: quay.io/maurycy_krzeminski/auth:0.1.1
    ports:
      - "8080:8080"
    environment:
      QUARKUS_LOG_HANDLER_GELF_ENABLED: false
      QUARKUS_OIDC_AUTH_SERVER_URL: "http://keycloak:8080/realms/quarkus"
      QUARKUS_OIDC_TOKEN_ISSUER: "http://keycloak:8080/realms/quarkus"
  keycloak:
    image: quay.io/maurycy_krzeminski/keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
        
  smtp:
     image: mailhog/mailhog
     ports:
     - "8082:8025"

