FROM jenkins/jenkins:lts

ENV JENKINS_USER admin
ENV JENKINS_PASS admin

# Skip initial setup
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false


USER root
RUN groupadd docker
RUN usermod -aG docker jenkins

RUN touch /var/run/docker.sock
RUN chmod 777 /var/run/docker.sock

RUN apt-get update \
    && apt-get install -qqy apt-transport-https ca-certificates curl gnupg2 software-properties-common 
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
RUN apt-get update  -qq \
    && apt-get install docker-ce -y
RUN usermod -aG docker jenkins
RUN apt-get clean
USER jenkins
RUN newgrp docker
# set default user attributes
ENV JENKINS_UID=1000
ENV JENKINS_GID=1000

ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/jenkins-casc.yaml
ENV PLUGIN_CONFIG /usr/share/jenkins/ref/plugins.txt

COPY plugins.txt ${PLUGIN_CONFIG}
RUN jenkins-plugin-cli -f ${PLUGIN_CONFIG}

COPY init.groovy.d/ /var/jenkins_home/init.groovy.d/
COPY jenkins-casc.yaml  ${CASC_JENKINS_CONFIG}
COPY job.groovy /jobdsl/job.groovy

USER jenkins

